#!/usr/bin/env bash
#Install nginx web server
apt-get update
apt-get install -y nginx

# start nginx service
sudo service nginx start

# Create index.html with "Hello World!"
sudo touch /var/www/html/index.html

echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx to apply changes
sudo service nginx restart
