#!/usr/bin/env bash

# Update package lists
# Install Nginx
# Create the HTML file that contains "Hello World!"
# Configure Nginx to serve the custom HTML file

apt-get update
apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

bash -c 'cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;
    }
}
EOF'
