#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update
sudo apt-get install -y nginx

start nginx service
sudo service nginx start

# Create index.html with "Hello World!"
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# update Nginx configuration to add redirection
sudo sed -i '/^}$/i \ \n\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Test Nginx configuration for syntax errors
sudo nginx -t 

# Restart Nginx to apply changes
service nginx restart
