#!/usr/bin/env bash
i=1
while [ $i -le 100 ]
do
	fb=$i%15
	f=$i%3
	b=$i%5
	if [[ $fb -eq 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $f -eq 0 ]]
	then
		echo "Fizz"
	elif [[ $b -eq 0 ]]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$(( i + 1 ))
done
