#!/usr/bin/env bash
#displays numbers and text at specific lop points

i=1

while [ $i -le 20 ]
do
  case $i in
    4) echo "$i\n bad luck from China";;
    9) echo "$i\n bad luck from Japan";;
    17) echo "$i\n bad luck from Italy";;
    *) echo $i;;
  esac
  (( i++ ))
done
