#!/usr/bin/env bash
#displays the content of the current directory in list format
#only the part of the name after the first dash is displayed

mylist=$(ls)

for i in $mylist; do
  echo "$i" | cut -d '-' -f2
done
