#!/usr/bin/env bash
# script that displays numbers from 1 to 100.
# displays FizzBuzz when the number is a multiple of 3 and 5
# displays Fizz when the number is multiple of 3
# displays Buzz when the number is a multiple of 5
# Otherwise, displays the number.

i=1
while [ $i -le 100 ]
do
	fb=$i%15
	f=$i%3
	b=$i%5
	if [[ $fb -eq 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $f -eq 0 ]]
	then
		echo "Fizz"
	elif [[ $b -eq 0 ]]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$(( i + 1 ))
done
